### PR TITLE
Replace Slack emoji shortcodes in event descriptions with images

### LINKED ISSUE #48: Use Slack emojis
In descriptions, `:emojiname:` should be rendered as an emoji on the website and pull the image URL from Slack

### PR DESCRIPTION
**Pull request by Glitch752**
Closes #48.

Event descriptions are currently stored as HTML, so we manipulate it as a string. I think we should look into storing Markdown, considering we don't use any HTML-specific features at the moment.

The code mimics how Scrapbook works: it uses the Badger API to download the Slack emoji list and replaces all occurrences of emoji shortcodes with an image. I cache the emoji list and use results from previous page loads (but re-fetch in the background) because we need to download _every_ emoji on each page load, which can take multiple seconds on slower networks. It would be nice if Badger could only send the emojis we need.

Thanks!

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝 Changed routes:


| [**/\[slug\]**](https://events-mpddlxx9e.hackclub.dev/[slug]) |
|:-:|
|<a href="https://events-mpddlxx9e.hackclub.dev/[slug]">Screenshot of /[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/CM5jwgLGU1W_po4RszMld94vYlWl7T3CItSstO6kdShc3SX6wMejYn5c920NLEMqeeuysV6LhF4KVt3251s08A.png">(view full size)</a> |







Commit b29e0520245bed09e8b29e51ef929cfa7459a91a (https://events-mpddlxx9e.hackclub.dev).

**Review by transcental — APPROVED** [review]
This looks great! Thanks for making this

**Comment by transcental** [comment]
> Event descriptions are currently stored as HTML, so we manipulate it as a string. I think we should look into storing Markdown, considering we don't use any HTML-specific features at the moment.

Not sure where you got this from, they're stored as markdown and parsed into HTML

**Comment by transcental** [comment]
Oh! @Glitch752 your PR breaks the styling for links! 

[This](https://events-o1tly9zhy.hackclub.dev/minecraft-fabric-modding-workshop/) is the previous deployment compared to [this](https://events-git-fork-glitch752-main.hackclub.dev/minecraft-fabric-modding-workshop/) one. 
image
image

**Comment by Glitch752** [comment]
Shoot; I'm so sorry I didn't catch that! I'll fix it as soon as possible.

**Comment by Glitch752** [comment]
Sorry again about that. Thankfully, it only requires a minor change. Fixed in #50.

**Pull request merged**
