### PR TITLE
Add CI (continuous integration)

### PR DESCRIPTION
**Pull request by gleich**
👋 Hello! I added CI to automatically make sure the `yarn run build` passes and that all files are formatted with prettier. I also added badges to the README which won't render yet until this PR gets merged. Hopefully, this helps!

### CODE REVIEW

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/\[slug\]**](https://events-git-fork-matt-gleich-main.hackclub.dev/[slug]) | [**/**](https://events-git-fork-matt-gleich-main.hackclub.dev/) |
|:-:|:-:|
|<a href="https://events-git-fork-matt-gleich-main.hackclub.dev/[slug]">Screenshot of /[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_xzBpGJ7xwgkY_NlTFQ4UQUpctU_.png">(view full size)</a> |<a href="https://events-git-fork-matt-gleich-main.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/j_DEl10pTZwpZqgj8ESrw4r_uVU_.png">(view full size)</a> |



| [**/past**](https://events-git-fork-matt-gleich-main.hackclub.dev/past) |
|:-:|
|<a href="https://events-git-fork-matt-gleich-main.hackclub.dev/past">Screenshot of /past</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/qcplwdT4BIlodwEm1c7cB09_VH4_.png">(view full size)</a> |



And 3 other routes:
- [**/api/events/all-monthly**](https://events-git-fork-matt-gleich-main.hackclub.dev/api/events/all-monthly)
- [**/api/events/upcoming-monthly**](https://events-git-fork-matt-gleich-main.hackclub.dev/api/events/upcoming-monthly)
- [**/api/events/upcoming**](https://events-git-fork-matt-gleich-main.hackclub.dev/api/events/upcoming)



Commit 7a2678c69af130b32e6dc51d678b0d53c30b5f0b (https://events-git-fork-matt-gleich-main.hackclub.dev).

**Comment by lachlanjc** [comment]
#### 📝Changed routes:


| [**/\[slug\]**](https://events-git-fork-matt-gleich-main.hackclub.dev/[slug]) | [**/**](https://events-git-fork-matt-gleich-main.hackclub.dev/) |
|:-:|:-:|
|<a href="https://events-git-fork-matt-gleich-main.hackclub.dev/[slug]">Screenshot of /[slug]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/IQY5Mw0o8_g5_Zz0ZPA7JuuAa5I_.png">(view full size)</a> |<a href="https://events-git-fork-matt-gleich-main.hackclub.dev/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/jhVcJQuskwdlHRMtOcYujCj_rbA_.png">(view full size)</a> |



| [**/past**](https://events-git-fork-matt-gleich-main.hackclub.dev/past) |
|:-:|
|<a href="https://events-git-fork-matt-gleich-main.hackclub.dev/past">Screenshot of /past</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/i_HRGskVyQ94dDL6P0Z5iMaG7m8_.png">(view full size)</a> |



And 3 other routes:
- [**/api/events/all-monthly**](https://events-git-fork-matt-gleich-main.hackclub.dev/api/events/all-monthly)
- [**/api/events/upcoming-monthly**](https://events-git-fork-matt-gleich-main.hackclub.dev/api/events/upcoming-monthly)
- [**/api/events/upcoming**](https://events-git-fork-matt-gleich-main.hackclub.dev/api/events/upcoming)



Commit f2f72125f9b57d9124d2c90598335a6aa17e5096 (https://events-git-fork-matt-gleich-main.hackclub.dev).

**Comment by gleich** [comment]
@lachlanjc any plans to merge this? I am just cleaning out some of my forks. No rush!

**Comment by lachlanjc** [comment]
https://github.com/hackclub/summer-scrapbook/pull/83#issuecomment-681024832

**Pull request closed without merging**
